# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)

version: '2.1'
services:
  drupal:
    image: naturalis/php-drupal:0.0.1
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${WEB_EXTERNAL_PORT:-8080}:80
    networks:
      - default
      - web
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    labels:
      - "traefik.backend=naturalis-drupal"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "${DRUPAL_SITE_URL:-traefik.frontend.rule=Host:drupal.naturalis.nl}"
    volumes:
      - ${BASE_PATH:-/data}/config:/root/config
      - ${BASE_PATH:-/data}/www/drupal:/var/www/html
      - ${BASE_PATH:-/data}/www/log/apache2:/var/log/apache2
      - ${BASE_PATH:-/opt}/project:/opt/project
  db:
    image: "mysql:5.7"
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-drupaltest}
        MYSQL_DATABASE: ${MYSQL_DATABASE:-drupaldb}
        MYSQL_USER: ${MYSQL_USER:-drupaluser}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-test123}
    networks:
        - default
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    ports:
        - "${MYSQL_EXTERNAL_PORT:-3306}:3306"
    volumes:
        - ${BASE_PATH:-/data}/database/mysqlconf:/etc/mysql/conf.d
        - ${BASE_PATH:-/data}/database/initdb:/docker-entrypoint-initdb.d
        - ${BASE_PATH:-/data}/database/db:/var/lib/mysql
        - ${BASE_PATH:-/data}/database/mysqllog:/var/log/mysql
  traefik:
    image: traefik:1.6.6
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - default
      - web
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.log:/var/log/traefik.log
      - ${TRAEFIK_TOML_FILE:-./traefik.dev.toml}:/traefik.toml
      - ${ACME_JSON:-./acme.json}:/acme.json

# run docker network create web before
networks:
  web:
    external: true
