[Global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "INFO"

[entrypoints]
  [entrypoints.http]
  address = ":80"

  [entrypoints.https]
  address = ":443"

[api]
  dashboard = true
  debug = false
  insecure = true

[http.routers]
  [http.routers.router0]
  entrypoints = ["http"]
  rule = "HostRegexp(`{any:.*}`)"
  middlewares = ["https-redirect"]
  service = "dummy"

[http.middlewares]
  [http.middlewares.https-redirect.redirectScheme]
    scheme = "https"

[http.services]
  [http.services.dummy.LoadBalancer]
     [[http.services.dummy.LoadBalancer.servers]]
        url = "http://192.168.0.1"

[certificatesResolvers.default.acme]
  email = "your-email@your-domain.org"
  storage = "/etc/traefik/acme.json"
  [certificatesResolvers.sample.acme.httpChallenge]
    # used during the challenge
    entryPoint = "http"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedbydefault = false
  [providers.file]
    filename = "dynamic-conf.toml"
